spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=1
#      routes:
#        - id: myRoute
#          filters:
#            - StripPrefix=1
#          predicates:
#            - Path=/{segment}/api/**
#          uri: lb://payment
#        - id: test
#          uri: lb://account
#          predicates:
#            - Path=/account/**